# Work around "scheduled workflows are automatically disabled when no repository activity has occurred in 60 days"
# https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#disabling-and-enabling-workflows
name: Keep Alive
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  activity:
    name: Simulate activity
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Push empty commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          commit: --allow-empty
          message: 'Keep alive'
